// src/components/tarot/tarotData.js
export const tarotDeck = [
    {
        id: 0,
        name: "The Fool",
        image: "/cards/fool.svg",
        description:
          "The Fool đại diện cho sự khởi đầu mới, niềm tin vào tương lai và sự ngây thơ. The Fool được đánh số 0, con số của tiềm năng vô hạn.",
        uprightMeaning: "Khởi đầu mới, sự ngây thơ, tự phát, tinh thần tự do",
        reversedMeaning: "Kìm hãm, liều lĩnh, mạo hiểm, ngây thơ",
        uprightKeywords: ["Khởi đầu", "Tự do", "Ngây thơ", "Tinh thần", "Phiêu lưu"],
        reversedKeywords: ["Liều lĩnh", "Ngây thơ", "Dại dột", "Rủi ro", "Bất cẩn"],
      },
      {
        id: 1,
        name: "The Magician",
        image: "/cards/magician.svg",
        description:
          "The Magician đại diện cho sự thể hiện, tài nguyên và hành động đầy cảm hứng. The Magician nhắc nhở chúng ta rằng chúng ta có tất cả các công cụ cần thiết để biến ước mơ thành hiện thực.",
        uprightMeaning: "Thể hiện, tài nguyên, sức mạnh, hành động đầy cảm hứng",
        reversedMeaning: "Thao túng, lập kế hoạch kém, tài năng chưa được khai thác",
        uprightKeywords: ["Thể hiện", "Sức mạnh", "Hành động", "Sáng tạo", "Kỹ năng"],
        reversedKeywords: ["Thao túng", "Ảo tưởng", "Lừa dối", "Lãng phí tài năng", "Bất an"],
      },
      {
        id: 2,
        name: "The High Priestess",
        image: "/cards/high-priestess.svg",
        description:
          "The High Priestess đại diện cho trực giác, kiến thức thiêng liêng và tiềm thức. Bà ngồi giữa thế giới ý thức và vô thức.",
        uprightMeaning: "Trực giác, kiến thức thiêng liêng, nữ tính thiêng liêng, tiềm thức",
        reversedMeaning: "Bí mật, mất kết nối với trực giác, rút lui và im lặng",
        uprightKeywords: ["Trực giác", "Bí ẩn", "Tâm linh", "Nhận thức", "Tiềm năng"],
        reversedKeywords: ["Bí mật", "Nhầm lẫn", "Hời hợt", "Đàn áp", "Động cơ ẩn"],
      },
      {
        id: 3,
        name: "The Empress",
        image: "/cards/empress.svg",
        description:
          "The Empress đại diện cho nữ tính, sự phong phú, sáng tạo và nuôi dưỡng. Bà là hình tượng người mẹ nuôi dưỡng và chăm sóc người khác.",
        uprightMeaning: "Nữ tính, vẻ đẹp, thiên nhiên, nuôi dưỡng, phong phú",
        reversedMeaning: "Khối sáng tạo, phụ thuộc vào người khác, trống rỗng",
        uprightKeywords: ["Phong phú", "Nuôi dưỡng", "Sinh sản", "Tăng trưởng", "Sáng tạo"],
        reversedKeywords: ["Phụ thuộc", "Ngột ngạt", "Trống rỗng", "Bỏ bê", "Vô sinh"],
      },
      {
        id: 4,
        name: "The Emperor",
        image: "/cards/emperor.svg",
        description:
          "The Emperor đại diện cho quyền lực, cấu trúc, kiểm soát và hình tượng người cha. Ông cung cấp cấu trúc và ổn định thông qua sức mạnh của ý chí.",
        uprightMeaning: "Quyền lực, thiết lập, cấu trúc, hình tượng người cha, lãnh đạo",
        reversedMeaning: "Thống trị, kiểm soát quá mức, cứng nhắc, thiếu linh hoạt",
        uprightKeywords: ["Quyền lực", "Cấu trúc", "Bảo vệ", "Logic", "Ổn định"],
        reversedKeywords: ["Thống trị", "Cứng nhắc", "Bướng bỉnh", "Lạnh lùng", "Kiểm soát"],
      },
      {
        id: 5,
        name: "The Hierophant",
        image: "/cards/hierophant.svg",
        description:
          "The Hierophant đại diện cho truyền thống, sự tuân thủ và trí tuệ tâm linh. Ông là mối liên kết giữa thần thánh và nhân loại.",
        uprightMeaning: "Trí tuệ tâm linh, niềm tin tôn giáo, sự tuân thủ, truyền thống, thể chế",
        reversedMeaning: "Niềm tin cá nhân, tự do, thách thức hiện trạng",
        uprightKeywords: ["Truyền thống", "Tâm linh", "Tuân thủ", "Đạo đức", "Đạo đức"],
        reversedKeywords: ["Nổi loạn", "Lật đổ", "Không theo quy ước", "Đổi mới", "Tự do"],
      },
      {
        id: 6,
        name: "The Lovers",
        image: "/cards/lovers.svg",
        description:
          "The Lovers đại diện cho các mối quan hệ, lựa chọn và hòa hợp. Nó thường đại diện cho những lựa chọn đi kèm với các mối quan hệ và hệ thống niềm tin cá nhân.",
        uprightMeaning: "Tình yêu, hòa hợp, mối quan hệ, sự phù hợp của giá trị, lựa chọn",
        reversedMeaning: "Tự yêu thương, bất hòa, mất cân bằng, không phù hợp với giá trị",
        uprightKeywords: ["Tình yêu", "Hòa hợp", "Kết nối", "Phù hợp", "Lựa chọn"],
        reversedKeywords: ["Bất hòa", "Mất cân bằng", "Xung đột", "Tách rời", "Lựa chọn tồi"],
      },
      {
        id: 7,
        name: "The Chariot",
        image: "/cards/chariot.svg",
        description:
          "The Chariot đại diện cho sự kiểm soát, ý chí, thành công và quyết tâm. The Chariot gợi ý rằng bạn đạt được chiến thắng thông qua việc duy trì kiểm soát môi trường xung quanh.",
        uprightMeaning: "Kiểm soát, ý chí, thành công, hành động, quyết tâm",
        reversedMeaning: "Tự kỷ luật, đối lập, thiếu phương hướng",
        uprightKeywords: ["Kiểm soát", "Phương hướng", "Ý chí", "Chiến thắng", "Khẳng định"],
        reversedKeywords: ["Hung hăng", "Thất bại", "Thiếu kiểm soát", "Đối lập", "Không có phương hướng"],
      },
      {
        id: 8,
        name: "Strength",
        image: "/cards/strength.svg",
        description:
          "Strength đại diện cho lòng can đảm, thuyết phục, ảnh hưởng và lòng trắc ẩn. Strength nhắc nhở chúng ta hành động từ tình yêu thương thay vì sợ hãi hoặc tức giận.",
        uprightMeaning: "Lòng can đảm, thuyết phục, ảnh hưởng, kiên nhẫn, lòng trắc ẩn",
        reversedMeaning: "Sức mạnh nội tâm, tự nghi ngờ, năng lượng thấp, cảm xúc thô",
        uprightKeywords: ["Can đảm", "Kiên nhẫn", "Trắc ẩn", "Ảnh hưởng", "Kiểm soát"],
        reversedKeywords: ["Tự nghi ngờ", "Yếu đuối", "Bất an", "Cảm xúc thô", "Dễ bị tổn thương"],
      },
      {
        id: 9,
        name: "The Hermit",
        image: "/cards/hermit.svg",
        description:
          "The Hermit đại diện cho việc tìm kiếm tâm hồn, nội tâm và hướng dẫn nội tâm. The Hermit gợi ý rằng bạn đang ở trong giai đoạn nội tâm, nơi bạn đang hướng sự chú ý vào bên trong.",
        uprightMeaning: "Tìm kiếm tâm hồn, nội tâm, ở một mình, hướng dẫn nội tâm",
        reversedMeaning: "Cô lập, cô đơn, rút lui",
        uprightKeywords: ["Nội tâm", "Cô độc", "Hướng dẫn", "Phản ánh", "Trí tuệ"],
        reversedKeywords: ["Cô lập", "Cô đơn", "Rút lui", "Từ chối", "Lưu đày"],
      },
      {
        id: 10,
        name: "Wheel of Fortune",
        image: "/cards/wheel-of-fortune.svg",
        description:
          "Wheel of Fortune đại diện cho may mắn, nghiệp, chu kỳ sống, số phận và bước ngoặt. Wheel nhắc nhở chúng ta rằng không có gì là vĩnh viễn.",
        uprightMeaning: "May mắn, nghiệp, chu kỳ sống, số phận, bước ngoặt",
        reversedMeaning: "Xui xẻo, kháng cự với sự thay đổi, phá vỡ chu kỳ",
        uprightKeywords: ["Thay đổi", "Chu kỳ", "Số phận", "Bước ngoặt", "Cơ hội"],
        reversedKeywords: ["Xui xẻo", "Kháng cự", "Phá vỡ chu kỳ", "Gián đoạn", "Thay đổi không mong muốn"],
      },
      {
        id: 11,
        name: "Justice",
        image: "/cards/justice.svg",
        description:
          "Justice đại diện cho công bằng, sự thật và luật pháp. Justice là một lá bài về nghiệp, nhân quả, và rằng mỗi hành động đều có một phản ứng.",
        uprightMeaning: "Công lý, công bằng, sự thật, nhân quả, luật pháp",
        reversedMeaning: "Bất công, thiếu trách nhiệm, không trung thực",
        uprightKeywords: ["Công lý", "Công bằng", "Sự thật", "Cân bằng", "Nghiệp"],
        reversedKeywords: ["Bất công", "Không công bằng", "Không trung thực", "Mất cân bằng", "Thiên vị"],
      },
      {
        id: 12,
        name: "The Hanged Man",
        image: "/cards/hanged-man.svg",
        description:
          "The Hanged Man đại diện cho sự hy sinh, buông bỏ và tử vì đạo. The Hanged Man gợi ý rằng bạn cần phải buông bỏ điều gì đó để tiến lên phía trước.",
        uprightMeaning: "Tạm dừng, đầu hàng, buông bỏ, quan điểm mới",
        reversedMeaning: "Trì hoãn, kháng cự, trì trệ, do dự",
        uprightKeywords: ["Đầu hàng", "Quan điểm", "Hy sinh", "Chờ đợi", "Treo"],
        reversedKeywords: ["Trì hoãn", "Kháng cự", "Trì trệ", "Do dự", "Đình trệ"],
      },
      {
        id: 13,
        name: "Death",
        image: "/cards/death.svg",
        description:
          "Death đại diện cho kết thúc, thay đổi, chuyển đổi và chuyển tiếp. Lá bài Death báo hiệu rằng một giai đoạn lớn trong cuộc sống của bạn đang kết thúc, và một giai đoạn mới sẽ bắt đầu.",
        uprightMeaning: "Kết thúc, thay đổi, chuyển đổi, chuyển tiếp",
        reversedMeaning: "Kháng cự với sự thay đổi, không thể tiếp tục",
        uprightKeywords: ["Chuyển đổi", "Kết thúc", "Thay đổi", "Chuyển tiếp", "Buông bỏ"],
        reversedKeywords: ["Kháng cự", "Đình trệ", "Sợ thay đổi", "Bám víu", "Suy tàn"],
      },
      {
        id: 14,
        name: "Temperance",
        image: "/cards/temperance.svg",
        description:
          "Temperance đại diện cho sự cân bằng, điều độ, kiên nhẫn và mục đích. Temperance gợi ý rằng bạn tìm thấy sự cân bằng trong bản thân và với người khác.",
        uprightMeaning: "Cân bằng, điều độ, kiên nhẫn, mục đích",
        reversedMeaning: "Mất cân bằng, thái quá, tự chữa lành, tái định hướng",
        uprightKeywords: ["Cân bằng", "Điều độ", "Kiên nhẫn", "Hòa hợp", "Tổng hợp"],
        reversedKeywords: ["Mất cân bằng", "Thái quá", "Bất hòa", "Không phù hợp", "Xung đột"],
      },
      {
        id: 15,
        name: "The Devil",
        image: "/cards/devil.svg",
        description:
          "The Devil đại diện cho bản ngã bóng tối, sự gắn bó, nghiện ngập và hạn chế. The Devil gợi ý rằng bạn cảm thấy bị mắc kẹt bởi những hạn chế và phụ thuộc của chính mình.",
        uprightMeaning: "Bản ngã bóng tối, gắn bó, nghiện ngập, hạn chế, tình dục",
        reversedMeaning: "Giải phóng niềm tin hạn chế, khám phá suy nghĩ đen tối, tách rời",
        uprightKeywords: ["Ràng buộc", "Nghiện ngập", "Chủ nghĩa vật chất", "Cám dỗ", "Gắn bó"],
        reversedKeywords: ["Tự do", "Giải phóng", "Tách rời", "Lấy lại quyền lực", "Tiết lộ"],
      },
      {
        id: 16,
        name: "The Tower",
        image: "/cards/tower.svg",
        description:
          "The Tower đại diện cho sự thay đổi đột ngột, biến động, hỗn loạn, tiết lộ và thức tỉnh. The Tower gợi ý rằng bạn đang trải qua một giai đoạn thay đổi lớn và biến động.",
        uprightMeaning: "Thay đổi đột ngột, biến động, hỗn loạn, tiết lộ, thức tỉnh",
        reversedMeaning: "Chuyển đổi cá nhân, sợ thay đổi, tránh thảm họa",
        uprightKeywords: ["Thảm họa", "Biến động", "Thay đổi đột ngột", "Tiết lộ", "Thức tỉnh"],
        reversedKeywords: ["Tránh né", "Trì hoãn thảm họa", "Sợ thay đổi", "Chuyển đổi", "Cảnh báo"],
      },
      {
        id: 17,
        name: "The Star",
        image: "/cards/star.svg",
        description:
          "The Star đại diện cho hy vọng, niềm tin, mục đích, đổi mới và tâm linh. The Star gợi ý rằng bạn đã trải qua nhiều thử thách và sẵn sàng tiến lên phía trước với sự lạc quan.",
        uprightMeaning: "Hy vọng, niềm tin, mục đích, đổi mới, tâm linh",
        reversedMeaning: "Thiếu niềm tin, tuyệt vọng, tự tin, mất kết nối",
        uprightKeywords: ["Hy vọng", "Cảm hứng", "Đổi mới", "Chữa lành", "Thanh thản"],
        reversedKeywords: ["Tuyệt vọng", "Nản lòng", "Vô vọng", "Tiêu cực", "Mất niềm tin"],
      },
      {
        id: 18,
        name: "The Moon",
        image: "/cards/moon.svg",
        description:
          "The Moon đại diện cho ảo tưởng, sợ hãi, lo lắng, tiềm thức và trực giác. The Moon gợi ý rằng bạn có thể đang chiếu nỗi sợ hãi vào hiện tại và tương lai dựa trên những trải nghiệm trong quá khứ.",
        uprightMeaning: "Ảo tưởng, sợ hãi, lo lắng, tiềm thức, trực giác",
        reversedMeaning: "Giải phóng nỗi sợ, cảm xúc bị đè nén, nhầm lẫn nội tâm",
        uprightKeywords: ["Ảo tưởng", "Sợ hãi", "Trực giác", "Tiềm thức", "Bí ẩn"],
        reversedKeywords: ["Nhầm lẫn", "Giải phóng nỗi sợ", "Đè nén", "Hiểu sai", "Rõ ràng"],
      },
      {
        id: 19,
        name: "The Sun",
        image: "/cards/sun.svg",
        description:
          "The Sun đại diện cho tích cực, vui vẻ, ấm áp, thành công và sức sống. The Sun gợi ý rằng bạn có sự rõ ràng trong tâm trí cho phép bạn tập trung vào những gì bạn muốn trong cuộc sống.",
        uprightMeaning: "Tích cực, vui vẻ, ấm áp, thành công, sức sống",
        reversedMeaning: "Đứa trẻ bên trong, cảm thấy buồn, quá lạc quan",
        uprightKeywords: ["Niềm vui", "Thành công", "Lạc quan", "Sức sống", "Tự tin"],
        reversedKeywords: ["Tiêu cực", "Trầm cảm", "Buồn bã", "Bi quan", "Kỳ vọng không thực tế"],
      },
      {
        id: 20,
        name: "Judgement",
        image: "/cards/judgement.svg",
        description:
          "Judgement đại diện cho sự phản ánh, tính toán, thức tỉnh, tái sinh và tiếng gọi nội tâm. Judgement gợi ý rằng bạn đang ở ngã ba đường và cần đưa ra quyết định sẽ ảnh hưởng đến tương lai của bạn.",
        uprightMeaning: "Phản ánh, tính toán, thức tỉnh, tái sinh, tiếng gọi nội tâm",
        reversedMeaning: "Tự nghi ngờ, phê bình nội tâm, bỏ qua tiếng gọi",
        uprightKeywords: ["Thức tỉnh", "Đổi mới", "Tính toán", "Tiếng gọi", "Tha thứ"],
        reversedKeywords: ["Tự nghi ngờ", "Từ chối", "Phê bình nội tâm", "Bỏ qua dấu hiệu", "Phủ nhận"],
      },
      {
        id: 21,
        name: "The World",
        image: "/cards/world.svg",
        description:
          "The World đại diện cho sự hoàn thành, thành tựu, du lịch và hoàn thành. The World gợi ý rằng bạn đã đạt đến cuối hành trình hoặc chu kỳ trong cuộc sống của bạn.",
        uprightMeaning: "Hoàn thành, tích hợp, thành tựu, du lịch",
        reversedMeaning: "Tìm kiếm sự khép lại cá nhân, đường tắt, trì hoãn",
        uprightKeywords: ["Hoàn thành", "Thành tựu", "Hoàn thành", "Tích hợp", "Du lịch"],
        reversedKeywords: ["Chưa hoàn thành", "Đường tắt", "Trì hoãn", "Thiếu khép lại", "Đình trệ"],
      },
  ];